const popupType = {
  MESSAGE: 'MESSAGE',
  ADMIN_LOGIN: 'ADMIN_LOGIN',
  PARTICIPANT_DETAIL: 'PARTICIPANT_DETAIL',
  LOADING: 'LOADING',
  ROOT_AUTH: 'ROOT_AUTH',
  FULL_SCREEN: 'FULL_SCREEN',
  EMAIL_AUTH: 'EMAIL_AUTH',
  ADMIN_PASSWORD_CHANGE: 'ADMIN_PASSWORD_CHANGE',
  ADMIN_PASSWORD_FIND: 'ADMIN_PASSWORD_FIND',
  MASTER_LOGIN: 'MASTER_LOGIN',
  QRCODE: 'QRCODE',
  ALARM_TALK_WRITING: 'ALARM_TALK_WRITING',
};

export default popupType; 