name: part5_mlkit_barcode_scanner_starter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  image_picker: ^1.0.2
  camera: ^0.10.5+3
  path: ^1.8.3
  path_provider: ^2.1.0
  google_mlkit_barcode_scanning: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
