import './globals.css'
import { Inter } from 'next/font/google'
import styles from './layout.module.css';
import Link from 'next/link';
import { Open_Sans } from 'next/font/google';
import { Nanum_Gothic } from 'next/font/google';

const sans = Open_Sans({subsets: ['latin']});
const gothic = Nanum_Gothic({
  weight: '700',
  subsets: ['latin'],
})

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={sans.className}>
      <body>
        <header className={styles.header}>
          <h1>demo note</h1>
          <nav className={styles.nav}>
            <Link href='/contact'>Contact</Link>
            <Link href='/about'>About</Link>  
            <Link href='/products'>Products</Link>  
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
